# Generated by Django 2.2.5 on 2020-02-10 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_register', '0002_auto_20200209_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
