# Generated by Django 2.2.5 on 2020-02-10 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_register', '0003_auto_20200210_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.CharField(max_length=3, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
