# Generated by Django 2.2.5 on 2020-02-10 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_register', '0004_auto_20200210_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
