# Generated by Django 2.2.5 on 2020-02-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_register', '0005_auto_20200210_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
