# Generated by Django 2.2.5 on 2020-02-12 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people_register', '0007_auto_20200210_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_register.City'),
        ),
    ]
